<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Codenotch/Usage.cs" Link="Usage.cs" />
    <Compile Include="../Codenotch/State.cs" Link="State.cs" />
    <Compile Include="../Codenotch/Providers.cs" Link="Providers.cs" />
  </ItemGroup>
</Project>
